[package]
name = "yt-post-dl-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = { version = "0.17.0", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version =  "1.39", features = ["rt-multi-thread", "macros"] }
linkify = "0.11.0"
reqwest = { version = "0.12.28",  default-features = false, features = ["native-tls"] }
url = "2.5.8"
anyhow = "1.0.102"
dotenvy = "0.15.7"
